### PR TITLE
About section of kiet page 

### PR DESCRIPTION
**Pull request by ashwin7455**

### CODE REVIEW

**Review by prabhat-021 — COMMENTED** [review]
Good code but what all are the changes in Client package-lock.json

**Comment by ashwin7455** [comment]
Sir, its just npm install kiya tha toh some dependency m kuch change aaya h noting confilcting . You can merge

**Comment by prabhat-021** [comment]
Ohk ashwin . i will see into it

**Comment by ashwin7455** [comment]
sure prabhat

**Pull request merged**
